
stages:
  prepare:
    cmd: python src/prepare_data.py
    deps:
      - data/raw
    outs:
      - data/processed
  train:
    cmd: python src/train.py
    deps:
      - data/processed
    outs:
      - model.pkl
